version: "3.9"
name: 'thisor'
services:
  # server:
  #   build:
  #     dockerfile: ./docker/server/dockerfile
  #   working_dir: /cmd
  #   ports:
  #     - "8080:8080"
  #   env_file:
  #     - .env
  #   volumes:
  #      - ./web:/cmd/web/:rw
  #   depends_on:
  #     - firestore

  firestore:
    build:
      context: ./docker/firebase
      dockerfile: dockerfile
    env_file:
      - .env
    ports:
      - "8787:8787"
      - "4000:4000"
    volumes:
       - ./docker/firebase/cache:/root/.cache/:rw
       - ./docker/firebase/data:/data:rw
    restart: unless-stopped